### ISSUE TITLE
Identify COVID-19 underreporting factor for the Omicron surge

### ISSUE THREAD

**Issue by simonleandergrimm** [naobservatory/p2ra#127]
As noted in `sars_cov_2.py`:
```
# Right now we use the same underreporting figure for both
# Spring/Fall 2020 and Winter 2021-2022.
#
# TODO: we can probably get a better undereporting figure for
# the omicron surge and this is likely too small.  The CDC 4x
# figure is not intended to cover this time period, this was
# after rapid tests were starting to be available, and omicron
# was relatively mild.

```
https://github.com/naobservatory/p2ra/blob/main/pathogens/sars_cov_2.py#LL99C5-L99C5

**Comment by simonleandergrimm** [comment]
Note to self that I might close this issue, depending on what we do with the Spurbeck data.

**Comment by jeffkaufman** [comment]
> There is no COVID-19 in the Spurbeck data

How so?  I see [18 reads](https://www.jefftk.com/mgs-counts/#q=sars-cov-2&mr=1e1&dna=1&rna=1&dna_rna=1&e_none=1&e_viral=1&c_viruses=1&c_bacteria=1&c_other=1&pinned=), at sites F, G, and H. They're on 2021-12-26 (and a little on 2022-01-09) which matches the omicron surge timing.

**Comment by simonleandergrimm** [comment]
Added a todo for myself to talk about this with Charlie.
