### ISSUE TITLE
Minor fix in influenza.py: Changing the variable name `public_health_labs_infections` to `clinical_labs_infections`

### ISSUE THREAD

**Issue by simonleandergrimm** [naobservatory/p2ra#128]
As noted in `influenza.py`, we are using clinical lab data, not public health lab data. @jeffkaufman Let me know if this fix is correct. 

[See code](https://github.com/naobservatory/p2ra/blob/main/pathogens/influenza.py#L165)

**Comment by jeffkaufman** [comment]
That's right; it should have been clinical.  Do you have a PR or should I make one?

**Comment by simonleandergrimm** [comment]
I'll do it!

**Comment by simonleandergrimm** [comment]
Closed, based on  #131
