### ISSUE TITLE
Potentially incorporate the share of positive tests into our influenza underreporting factor. (flag with Dan)

### ISSUE THREAD

**Issue by simonleandergrimm** [naobservatory/p2ra#129]
https://github.com/naobservatory/p2ra/blob/00ec297987190b3260e25ba3f4ea36905164a648/pathogens/influenza.py#L139-L186

We currently compute yearly influenza underreporting by dividing `official_cdc_incidence` by `yearly_positive_tests`. But we might be able to get a more fine-grained underreporting factor by also incorporating the share of positive tests. E.g., if at the beginning of a new influenza pandemic, overall positive tests only increase slowly, but positive testing share rises rapidly, there is likely outsized underreporting for a short time period. We currently do not incorporate this information.

Then again, it might be too much conceptual work to integrate this into our current model. I will flag this with Dan at our next group meeting.

**Comment by dp-rice** [comment]
@simonleandergrimm was scrolling open issues and saw my name. Is this still relevant?

**Comment by simonleandergrimm** [comment]
Given the lack of influenza in our metagenomic sequencing data, more precision here won't add much.
