### ISSUE TITLE
Currently it is unclear when the NORS Outbreak data starts, only that it ends in 2021.

### ISSUE THREAD

**Issue by simonleandergrimm** [naobservatory/p2ra#130]
https://github.com/naobservatory/p2ra/blob/00ec297987190b3260e25ba3f4ea36905164a648/pathogens/norovirus.py#LL79C1-L94C41

**Comment by jeffkaufman** [comment]
The data goes back a long way, but the older data includes fewer states so naively comparing outbreak numbers won't work.  HISTORY_START holds the first year we're using.
