### ISSUE TITLE
Typesafe TaxIDs

### ISSUE THREAD

**Issue by dp-rice** [naobservatory/p2ra#28]
Currently TaxIDs are represented as ints in the prevalence code and strings in the MGS data. This makes it easy to make mistakes, e.g. when searching a dict. Semantically TaxIDs are neither (it doesn't make sense to do arithmetic or string operations on them). I propose to make a new datatype `TaxID = NewType("TaxID", int)` so we can use the type system to check their usage.

**Comment by jeffkaufman** [comment]
Yup; still happy to see this fixed!
