### ISSUE TITLE
Pull MGS data from a tag in the pipeline repo

### ISSUE THREAD

**Issue by dp-rice** [naobservatory/p2ra#51]
Currently we pull from a fixed commit, but it would be nice to use tags so it's clearer what we're doing and easier to update.

**Comment by jeffkaufman** [comment]
@dp-rice I just updated permissions so you should be able to create tags now

**Comment by dp-rice** [comment]
Thanks, @jeffkaufman. Any opinions about what we call the tags? I'm thinking something like `data-0.1`, `data-0.1.1` etc using semantic versioning. We don't have to over-engineer it but it would be nice to be able to keep track of the history.

**Comment by jeffkaufman** [comment]
Two ideas that come to mind are (a) use the date we created the tag and always tag new ones or (b) have a tag that represents "stable data in the current format" (stable-<semver>) and repeatedly push to that tag when it shouldn't be a breaking change.  I'd lean towards (a), keep it simple?
