### ISSUE TITLE
Make an estimate for flu

### ISSUE THREAD

**Issue by jeffkaufman** [naobservatory/p2ra#82]
Flu is an RNA virus, so to match with the data we have so far we're most interested in:

* SoCal, Fall 2020
* NoCal, Summer 2020
* Ohio, Winter 2021-2022

If we can get separate estimates for Flu A and Flu B that's ideal, though it looks like in a lot of surveillance this isn't tracked?

**Comment by simonleandergrimm** [comment]
I believe you can close this issue
